name: "CI"
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  run_specs:
    name: Rspec
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      CI: true
      RAILS_ENV: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Run specs
        run: bundle exec rspec --format documentation --format RspecJunitFormatter --out tmp/rspec.xml

      - name: Publish Rspec Test Results
        uses: mikepenz/action-junit-report@v4
        if: success() || failure()
        with:
          check_name: Rspec Test Results
          report_paths: tmp/rspec.xml
          detailed_summary: true
        env:
          GITHUB_STEP_SUMMARY: true
