name: Publish New Gem Version to RubyGems.org

on:
  release:
    types: [published]

permissions:
  id-token: write
  contents: write

jobs:
  push:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v6
        with: { persist-credentials: false }
      - uses: ruby/setup-ruby@v1
        with: { bundler-cache: true }
      - uses: rubygems/release-gem@v1
