name: CI

on:
  push:
    branches: [ main ]
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}-${{ github.event.ref }}
  cancel-in-progress: true

env:
  BUNDLE_WITHOUT: production
  CI: true
  RAILS_ENV: test
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: password
  SECRET_KEY_BASE: '123' # Dummy value for tests

jobs:
  project-stats:
    name: Project Stats
    runs-on: blacksmith-4vcpu-ubuntu-2404
    timeout-minutes: 3
    steps:
      - uses: actions/checkout@v6
      - uses: RoleModel/actions/project-stats@v3

  compile-assets:
    name: Compile Assets
    runs-on: blacksmith-4vcpu-ubuntu-2404
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v6
      - uses: RoleModel/actions/compile-assets@v3
        id: check-asset-cache

  non-system-test:
    name: Linting, Security, & Ruby Tests
    runs-on: blacksmith-4vcpu-ubuntu-2404
    timeout-minutes: 5

    services:
      postgres:
        image: postgres:17
        ports:
          - "5432:5432"
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password

    steps:
      - uses: actions/checkout@v6
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - run: bin/bundler-audit
      - run: bin/brakeman --quiet --no-pager --exit-on-warn --exit-on-error

      - uses: RoleModel/actions/linting-and-non-system-tests@v3
        with:
          needs-compiled-assets: false
          linting_step_required: true
          linting_step_command: bundle exec rubocop --format github

  system-test:
    name: Ruby System Tests
    runs-on: blacksmith-8vcpu-ubuntu-2404
    timeout-minutes: 10
    needs: compile-assets

    services:
      postgres:
        image: postgres:17
        ports:
          - "5432:5432"
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password

    steps:
      - uses: actions/checkout@v6
      - uses: RoleModel/actions/system-tests@v3
